### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by einenlum** [felipe-augusto/linguee#8]
@felipe-augusto It seems there is no github release or git tag on the project.
Do you know where the npm v1.0.0 leads? It seems it's causing problems : https://github.com/felipe-augusto/linguee/issues/7

I think we should release at least a patch release and update it on npm. What do you think? :)

**Comment by felipe-augusto** [comment]
@Einenlum I will do this ASAP!

**Comment by felipe-augusto** [comment]
Done!

**Comment by einenlum** [comment]
Thanks @felipe-augusto ! But I don't see any release [here](https://github.com/felipe-augusto/linguee/releases). Do I miss something? ^^

**Comment by felipe-augusto** [comment]
I think I missed something, haha. I never did that, can you check if everything is correct?

**Comment by einenlum** [comment]
Seems perfect, thanks! :)

To automate my release process with npm and github I generally use [release-it](https://github.com/webpro/release-it). It simplifies things a lot!
